spring:
  profiles:
    active: test

  servlet:
    multipart:
      max-file-size: 25MB   # uploaded_file_size default 1MB max 10MB
      max-request-size: 25MB

  mvc:
    static-path-pattern: any-pattern

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # running log
    map-underscore-to-camel-case: true  # Mapping: phone_number => phoneNumber

  global-config:
    db-config:
      id-type: AUTO   # snow_flake auto_increment
